### ISSUE TITLE
star了，非常棒！另外请问如何获取多个页面的元素？

### ISSUE THREAD

**Issue by Briy09** [sedgwickz/jsonHunter#1]
比如获取 V2EX -分享创造 的 第1页到第10页 的 贴子标题及链接？
请求url为以下：
https://www.v2ex.com/go/create?p=1
https://www.v2ex.com/go/create?p=2
……
https://www.v2ex.com/go/create?p=10

**Comment by sedgwickz** [comment]
网站本身不支持批量查询，但如果对爬虫稍微有点了解，自己利用接口实现这个不难。另这个问题涉及版权问题，抱歉无法回答。
